# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0002_auto_20170325_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni_paciente',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
